### ISSUE TITLE
Claiming multiple claimpays at once doesn't seem to work.

### ISSUE THREAD

**Issue by lukestokes** [eosdac/eosdac-contracts#26] opened 2019-06-21 15:38 UTC
Check out https://eosq.app/tx/7f0271099e22efcdbf4d9d272a972bcf5a23aadd74abe21c3c5d8b6107d0e7a3

![image](https://user-images.githubusercontent.com/344748/59934060-b6e38200-9418-11e9-9d7a-f9709a53d179.png)

This one worked: https://eosq.app/tx/3711de77c6dbe78003c75d8db8eb6ed3c366b5269f235dd6a360eb5c0f41a9f7

These two did not:

https://eosq.app/tx/422b1729275e32871917a9becf45466e943a16de9f010d9715092c27e5b0a813
https://eosq.app/tx/b9ab0c6d7bc03986d1d6fc10391055f85536bb9849cd9c96138019366d4de90e

This is the error:

> deferred transaction with the same sender_id and payer already exists

Seems it's not taking into account the different `payid`'s?

**Comment by lukestokes** [comment] 2019-07-25 20:23
What's the latest on this? I have two payments queued up to test, if we want to (currently the button is disabled in the UI)

**Comment by piecesnbits** [comment] 2019-07-25 20:40
@lukestokes it is fixed in the contract. however the fix doesn't work for pending pays before the fix was applied. at least that is my understanding. so I have disabled the button until all if not most "old" pays are claimed.

**Comment by dallasjohnson** [comment] 2019-08-10 14:17
I believe this is done but needs to be tested for a while to ensure it is fixed since the cause was not 100% understood. Will leave the issue open for now.

**Comment by michaeljyeates** [comment] 2019-08-21 17:13
The new way of claiming pay means that even if the payments fail, the pending pay row is not deleted.  This means it is a lot safer now to try to claim all so i think we should enable the button in the mainnet member client again and ask someone to test @lukestokes

**Closed** 2019-09-01 19:11 UTC
